# Generated by Django 5.0.6 on 2024-06-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecurrenceType',
            new_name='Event',
        ),
    ]
